# build stage
FROM node:alpine as builder

WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

COPY packages/server/package*.json ./packages/server/
COPY packages/common/package*.json ./packages/common/

RUN yarn --pure-lockfile --non-interactive  

COPY packages/server/ ./packages/server
COPY packages/common/ ./packages/common

COPY packages/server-dev.sh ./packages/

WORKDIR /usr/src/app/packages

RUN chmod +x server-dev.sh

CMD ["/bin/sh","server-dev.sh"]