# build stage
FROM node:alpine

WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

COPY packages/web/package*.json ./packages/web/
COPY packages/common/package*.json ./packages/common/

RUN yarn --pure-lockfile --non-interactive  

COPY packages/web/ ./packages/web
COPY packages/common/ ./packages/common

COPY ./web-dev.sh .

RUN chmod +x web-dev.sh

CMD ["/bin/sh", "./web-dev.sh"]

# WORKDIR /usr/src/app/packages/web

# CMD ["yarn", "start"]


